[toolchain]
anchor_version = "0.27.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
alyra_sign_presence = "45bABCXebKAgUdv5XYveewzCtcxZ7fmisyeoo8rbFymZ"
alyra_sign_registry = "4PU2tkWkdTUD4SwczHkc5ttGoRS3hAVQqVfc7gThfRWC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
copy-idl = "cp target/idl/*.json src/idl/"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
